# Generated by Django 3.2.6 on 2021-08-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_events_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
