# Generated by Django 3.2.6 on 2021-08-27 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_events_event_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='event_time',
            new_name='event_date',
        ),
    ]
